### ISSUE TITLE
example configuration needs refactor

### ISSUE THREAD

**Issue by peppelinux** [rohe/fedservice#22]
following this breaking change

https://github.com/IdentityPython/oidc-op/commit/e25bf716fad5b454d2c3f462adaf400cb70a4668

**Comment by rohe** [comment]
Didn't I issue a puller quest for that ?
No new release of OIDC-op though.

**Comment by peppelinux** [comment]
mmmhh fedservice uses [oiscop v2.3.4](https://github.com/rohe/fedservice/blob/master/setup.py#L69) and has a lot of old configurations regarding keys

````
fedservice/example/openid_provider/umu$ find . -type f | xargs grep keys
./conf.json:  "oidc_keys": {
./conf.json:      "keys": {
./conf.json:        "keys": {
./conf.json:          "private_path": "private/fed_keys.json",
./conf.json:          "public_path": "static/fed_keys.json",

# ... many others ...
````

It's just a note to keep attention of this pending action

**Comment by rohe** [comment]
Don't bother with fedservice/example/openid_provider and the likes they are not to be used.

**Comment by peppelinux** [comment]
https://github.com/rohe/fedservice/tree/master/example#federation-example
